version: '3.0'

services:
  zoo:
    image: zookeeper
    restart: always
    hostname: zoo
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      #ZOO_SERVERS: server.1=0.0.0.0:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888

  ui:
    image: maauso/zkui
    links:
      - zoo:zoo
    environment:
      ZKLIST: zoo:2181
    ports:
      - 19090:9090

